from setuptools import setup, find_packages

setup(
    name="acwmf",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy>=1.20.0",
        "networkx>=2.6.0",
        "redis>=4.0.0",
        "torch>=1.10.0",
        "transformers>=4.15.0",
        "matplotlib>=3.4.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "scipy>=1.7.0",
        "asyncio>=3.4.3",
        "flask>=2.0.0",
        "flask-cors>=3.0.0",
    ],
    author="angrysky56",
    author_email="your.email@example.com",
    description="Adaptive Compressed World Model Framework",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/angrysky56/Adaptive-Compressed-World-Model-Framework",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.8",
)
